export const welcomeText = [
  "hello",
  "bonjour",
  "hallo",
  "merhaba",
  "سلام",
  "γειά σας",
  "hallo",
  "你好",
  "ciao",
  "hola",
  "こんにちは",
  "hej",
  "hej",
  "สวัสดี",
  "olá",
  "cześć",
  "salut",
  "привет",
  "שלום",
  "bonjour",
  "hallo",
  "merhaba",
  "سلام",
  "γειά σας",
  "hallo",
  "你好",
  "ciao",
  "hola",
  "こんにちは",
  "hej",
  "hej",
  "สวัสดี",
  "olá",
  "cześć",
  "salut",
  "привет",
  "hello!",
  "שלום",
];

export const myNameIsText = [
  "my name is",
  "mon nom est",
  "mijn naam is",
  "benim adım",
  "اسم من هو",
  "το όνομά μου είναι",
  "mein Name ist",
  "我的名字是",
  "il mio nome è",
  "mi nombre es",
  "私の名前は",
  "mitt namn är",
  "mitt navn er",
  "ชื่อของฉันคือ",
  "meu nome é",
  "moje imię to",
  "numele meu este",
  "Меня зовут",
  "שמי הוא",
  "my name is",
  "mon nom est",
  "mijn naam is",
  "benim adım",
  "اسم من هو",
  "το όνομά μου είναι",
  "mein Name ist",
  "我的名字是",
  "il mio nome è",
  "mi nombre es",
  "私の名前は",
  "mitt namn är",
  "mitt navn er",
  "ชื่อของฉันคือ",
  "meu nome é",
  "moje imię to",
  "numele meu este",
  "Меня зовут",
  "my name is",
  "שמי הוא",
];

export const aboutMeText = `As a musician turned developer, I've embraced the world of programming, creating applications, and websites. My coding journey began during the lockdowns in 2020, and I've since tackled diverse projects, demonstrating a can-do attitude and a passion for clean code.
\n

My multilingual skills, including native proficiency in French and English, are assets that enable effective communication in diverse teams.
\n
I'm excited about opportunities to contribute my skills and enthusiasm to innovative organizations, such as Itransition, Civica, and Acurable, and I look forward to discussing how I can make a meaningful impact on your team.`;
